SELECT u.display_name AS Name, 
	(
	SELECT COALESCE(SUM(tl.hours),0)
	FROM time_log AS tl
	WHERE time_at 
		BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+6 DAY, "%Y-%m-%d 00:00:00") 
		AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+6 DAY, "%Y-%m-%d 23:59:59") 
	AND tl.user_id = u.id
	) AS Sun, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+5 DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+5 DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Mon, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+4 DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+4 DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Tue, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+3 DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+3 DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Wed, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+2 DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+2 DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Thur, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+1 DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+1 DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Fri, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00')) DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00')) DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Sat, (
SELECT COALESCE(SUM(tl.hours),0)
FROM time_log AS tl
WHERE time_at BETWEEN DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00'))+6 DAY, "%Y-%m-%d 00:00:00") AND DATE_FORMAT(CONVERT_TZ(CURDATE(), '+0:00', '-6:00') - INTERVAL DAYOFWEEK(CONVERT_TZ(CURDATE(), '+0:00', '-6:00')) DAY, "%Y-%m-%d 23:59:59") AND tl.user_id = u.id) AS Total
FROM users u
WHERE u.is_staff = 1;